const form=document.getElementById("searchForm"),input=document.getElementById("profileUrl"),button=document.getElementById("searchBtn"),statusBox=document.getElementById("status"),profileCard=document.getElementById("profileCard"),profileName=document.getElementById("profileName"),profileUrlText=document.getElementById("profileUrlText"),storyCount=document.getElementById("storyCount"),avatarLetter=document.getElementById("avatarLetter"),viewer=document.getElementById("viewer"),storyGrid=document.getElementById("storyGrid"),counter=document.getElementById("counter"),modal=document.getElementById("modal"),modalContent=document.getElementById("modalContent"),closeModal=document.getElementById("closeModal"),prev=document.getElementById("prev"),next=document.getElementById("next"),progress=document.getElementById("progress"),modalIndex=document.getElementById("modalIndex");
let stories=[],currentIndex=0;
const messages=["আচ্ছা দেখি আজকে নতুন কী কাণ্ড… 👀","Story দেখা হচ্ছে… শান্ত থাকো 😌","কিছুই দেখিনি ভাই, আমরা এখানে ছিলামই না 🤫","Sohag ভাই, খবর কিন্তু আসতেছে 👀","Pavel + Sohag Investigation Department কাজ করছে… 😂"];
function setStatus(m,error=false){statusBox.textContent=m;statusBox.classList.remove("hidden","error");if(error)statusBox.classList.add("error")}
function clearResults(){profileCard.classList.add("hidden");viewer.classList.add("hidden");storyGrid.innerHTML="";stories=[]}
function renderStories(){storyGrid.innerHTML="";stories.forEach((s,i)=>{const card=document.createElement("article");card.className="story";if(s.type==="video"){const v=document.createElement("video");v.src=s.url;v.muted=true;v.preload="metadata";card.appendChild(v)}else{const img=document.createElement("img");img.src=s.url;img.loading="lazy";img.alt=`Story ${s.storyNo}`;card.appendChild(img)}const b=document.createElement("div");b.className="badge";b.textContent=`${s.type==="video"?"VIDEO":"PHOTO"} • ${s.quality||"ORIGINAL"}`;card.appendChild(b);card.onclick=()=>openModal(i);storyGrid.appendChild(card)});counter.textContent=`${stories.length} stories`}
function renderProgress(){progress.innerHTML="";stories.forEach((_,i)=>{const el=document.createElement("i");if(i===currentIndex)el.className="active";progress.appendChild(el)})}
function openModal(i){currentIndex=i;const s=stories[i];modalContent.innerHTML="";renderProgress();modalIndex.textContent=`${i+1} / ${stories.length}`;if(s.type==="video"){const v=document.createElement("video");v.src=s.url;v.controls=true;v.autoplay=true;v.playsInline=true;modalContent.appendChild(v)}else{const img=document.createElement("img");img.src=s.url;img.alt=`Story ${s.storyNo}`;modalContent.appendChild(img)}modal.classList.remove("hidden")}
function closeViewer(){modal.classList.add("hidden");modalContent.innerHTML=""}
function move(d){if(!stories.length)return;currentIndex=(currentIndex+d+stories.length)%stories.length;openModal(currentIndex)}
closeModal.onclick=closeViewer;prev.onclick=()=>move(-1);next.onclick=()=>move(1);modal.onclick=e=>{if(e.target===modal)closeViewer()};document.onkeydown=e=>{if(modal.classList.contains("hidden"))return;if(e.key==="Escape")closeViewer();if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)};
form.onsubmit=async e=>{e.preventDefault();const url=input.value.trim();if(!url)return;clearResults();setStatus(messages[Math.floor(Math.random()*messages.length)]);button.disabled=true;button.innerHTML="<span>খোঁজা হচ্ছে…</span><b>⌛</b>";try{const r=await fetch("/api/stories",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profileUrl:url})});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||"Story পাওয়া যায়নি।");statusBox.classList.add("hidden");profileName.textContent=data.profile?.name||"Facebook profile";profileUrlText.textContent=data.profile?.profileUrl||url;avatarLetter.textContent=(data.profile?.name||"B").trim().charAt(0).toUpperCase();storyCount.textContent=data.total;profileCard.classList.remove("hidden");stories=data.stories||[];renderStories();viewer.classList.remove("hidden")}catch(err){setStatus(err.message||"Something went wrong.",true)}finally{button.disabled=false;button.innerHTML="<span>View Stories</span><b>→</b>"}};
